COMP2139_KRN_GENIUS/COMP2139_KRN_GENIUS/Controllers/HomeController.cs
using COMP2139_KRN_GENIUS.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace COMP2139_KRN_GENIUS.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        [Route("about")]
        public ViewResult About()
        {
            return View();
        }
    }
}

COMP2139_KRN_GENIUS/COMP2139_KRN_GENIUS/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using COMP2139_KRN_GENIUS.Models;
using COMP2139_KRN_GENIUS.Models.ViewModels;

namespace COMP2139_KRN_GENIUS.Controllers
{
    public class RegistrationController : Controller
    {
        private MainContext context { get; set; }
        public RegistrationController(MainContext ctx)
        {
            context = ctx;
        }

        [HttpGet]
        [Route("registration/getcustomer")]
        public ViewResult Get()
        {
            var reg = new RegistrationViewModel
            {
                CustomerId = 0,
                Customers = context.Customers.OrderBy(m => m.CustomerId).ToList()
            };

            return View(reg);
        }
        [HttpPost]
        [Route("registration/getcustomer")]
        public IActionResult Get(RegistrationViewModel regVM) 
        {
            if (regVM.CustomerId == 0)
            {
                TempData["message"] = "Please select a Customer.";
                regVM.Customers = context.Customers.OrderBy(m => m.CustomerId).ToList();
                return View(regVM);
            }
            
            return RedirectToAction("List", new { id = regVM.CustomerId });
        }

        public ViewResult List(int id)
        {
            HttpContext.Session.SetInt32("customerId", id);
            Customer? c = context.Customers.Where(c => c.CustomerId == id).FirstOrDefault();

            var reg = new RegistrationViewModel
            {
                Registration = new Registration { CustomerId = id, ProductId = 0 },
                CustomerName = c.FirstName + " " + c.LastName,
                Registrations = context.Registrations.Where(r => r.CustomerId == id).OrderBy(r => r.ProductId).ToList(),
                Products = context.Products.OrderBy(m => m.ProductId).ToList()
            };

            return View(reg);
        }

        [HttpPost]
        public RedirectToActionResult Register(RegistrationViewModel regVM)
        {
            if (regVM.Registration.ProductId == 0)
            {
                TempData["message"] = $"Please select a product.";
            }
            else
            {
                List<Registration> reg = context.Registrations.Where(
                    r =>
                    r.CustomerId == HttpContext.Session.GetInt32("customerId") &&
                    r.ProductId == regVM.Registration.ProductId).ToList();

                if (reg.Count == 0)
                {
                    Product product = context.Products.Where(p => p.ProductId == regVM.Registration.ProductId).FirstOrDefault();
                    TempData["productMessage"] = $"{product.Name} was added successfully.";
                    context.Registrations.Add(regVM.Registration);
                    context.SaveChanges();
                }
                else
                {
                    TempData["message"] = $"Cannot register the same pair of customer and product.";
                }
            }
            return RedirectToAction("List", new { id = HttpContext.Session.GetInt32("customerId") });
        }

        [HttpGet]
        public ViewResult Delete(int id)
        {
            var reg = new RegistrationViewModel
            {
                Registration = new Registration { ProductId = id, CustomerId = (int)HttpContext.Session.GetInt32("customerId") },
                Customers = context.Customers.Where(r => r.CustomerId == HttpContext.Session.GetInt32("customerId")).ToList(),
                Products = context.Products.Where(r => r.ProductId == id).ToList()
            };

            return View(reg);
        }
        [HttpPost]
        public RedirectToActionResult Delete(RegistrationViewModel regVM)
        {
            context.Registrations.Remove(regVM.Registration);
            context.SaveChanges();
            TempData["productMessage"] = $"{regVM.ProductName} was deleted successfully.";
            return RedirectToAction("List", new { id = HttpContext.Session.GetInt32("customerId") });
        }
    }
}

COMP2139_KRN_GENIUS/COMP2139_KRN_GENIUS/Controllers/TechIncidentController.cs
using Microsoft.AspNetCore.Mvc;
using COMP2139_KRN_GENIUS.Models;
using COMP2139_KRN_GENIUS.Models.ViewModels;

namespace COMP2139_KRN_GENIUS.Controllers
{
    public class TechIncidentController : Controller
    {
        private MainContext context { get; set; }
        public TechIncidentController(MainContext ctx)
        {
            context = ctx;
        }

        [HttpGet]
        public ViewResult Get()
        {
            var techVM = new TechIncidentViewModel
            {
                id = 0,
                Technicians = context.Technicians.OrderBy(m => m.TechnicianId).ToList()
            };
            return View(techVM);
        }
        [HttpPost]
        public IActionResult Get(TechIncidentViewModel techVM)
        {
            if (techVM.id == 0)
            {
                TempData["message"] = "Please select a Technician.";
                techVM.Technicians = context.Technicians.OrderBy(m => m.TechnicianId).ToList();
                return View(techVM);
            }
            return RedirectToAction("List", new { id = techVM.id });
        }

        [HttpGet]
        public ViewResult List(int id)
        {
            var incidents = from incident in context.Incidents
                            join customer in context.Customers on incident.CustomerId equals customer.CustomerId
                            join product in context.Products on incident.ProductId equals product.ProductId
                            where incident.TechnicianId == id && incident.DateClosed == null
                            select new
                            {
                                IncidentId = incident.IncidentId,
                                Title = incident.Title,
                                Customer = customer.FirstName + " " + customer.LastName,
                                Product = product.Name,
                                DateOpened = incident.DateOpened
                            };

            HttpContext.Session.SetInt32("techId", id);
            var tech = from technician in context.Technicians where technician.TechnicianId == id select new { Name = technician.Name };
            ViewBag.Technician = tech.ToList()[0].Name;
            return View(incidents.ToList());
        }

        [HttpGet]
        public ViewResult Edit(int id)
        {
            HttpContext.Session.SetInt32("techIncidentId", id);
            Incident incident = context.Incidents.Find(id);

            var incidentVM = new IncidentViewModel
            {
                Incident = incident,
                Technician = context.Technicians.Find(incident.TechnicianId),
                Customer = context.Customers.Find(incident.CustomerId),
                Product = context.Products.Find(incident.ProductId),
            };

            return View("Edit", incidentVM);
        }
        [HttpPost]
        public IActionResult Edit(IncidentViewModel incidentVM)
        {
            if (ModelState.IsValid)
            {
                context.Incidents.Update(incidentVM.Incident);
                context.SaveChanges();
                return RedirectToAction("List", new { id = HttpContext.Session.GetInt32("techId") });
            }
            else
            {
                Incident incident = context.Incidents.Find(HttpContext.Session.GetInt32("techIncidentId"));

                var inciVM = new IncidentViewModel
                {
                    Incident = incident,
                    Technician = context.Technicians.Find(incident.TechnicianId),
                    Customer = context.Customers.Find(incident.CustomerId),
                    Product = context.Products.Find(incident.ProductId),
                };
                return View(inciVM);
            }
        }
    }
}

COMP2139_KRN_GENIUS/COMP2139_KRN_GENIUS/Views/Home/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!-- Contact Us -->
<section id="cont">
    <div id="cont-page">
        <div class="cont-title">
            <h1>CONTACT US</h1>
            <p>Meet some of the people you'll talk to by the way you'd like</p>
        </div>
        <div class="cont-row">
            <div class="team-info">
                <img class="team-img" src="~/lib/img/1sad.jpg" />
                <div class="team-desc">
                    <h2>Seunghun Yim</h2>
                    <h5>Back-End Developer</h5>
                </div>
                <div class="sns-icons">
                    <ul>
                        <li>
                            <a href="mailto:seunghun.yim@georgebrown.ca" target="_blank">
                                <img src="~/lib/img/mail.png" alt="email" />
                            </a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com" target="_blank">
                                <img src="~/lib/img/inst.png" alt="instagram" />
                            </a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com" target="_blank">
                                <img src="~/lib/img/fb.png" alt="facebook" />
                            </a>
                        </li>
                        <li>
                            <a href="https://www.twitter.com" target="_blank">
                                <img src="~/lib/img/link.png" alt="twitter" />
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="team-info">
                <img class="team-img" src="~/lib/img/3anger.jpg" />
                <div class="team-desc">
                    <h2>Jooyoung Song</h2>
                    <h5>Back-End Developer</h5>
                </div>
                <div class="sns-icons">
                    <ul>
                        <li>
                            <a href="mailto:jooyoung.song@georgebrown.ca" target="_blank">
                                <img src="~/lib/img/mail.png" alt="email" />
                            </a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com" target="_blank">
                                <img src="~/lib/img/inst.png" alt="instagram" />
                            </a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com" target="_blank">
                                <img src="~/lib/img/fb.png" alt="facebook" />
                            </a>
                        </li>
                        <li>
                            <a href="https://www.twitter.com" target="_blank">
                                <img src="~/lib/img/link.png" alt="twitter" />
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="team-info">
                <img class="team-img" src="~/lib/img/2joy.jpg" />
                <div class="team-desc">
                    <h2>Yoonhee Kim</h2>
                    <h5>Front-End Developer</h5>
                </div>
                <div class="sns-icons">
                    <ul>
                        <li>
                            <a href="mailto:yoonhee.kim@georgebrown.ca" target="_blank">
                                <img src="~/lib/img/mail.png" alt="email" />
                            </a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com" target="_blank">
                                <img src="~/lib/img/inst.png" alt="instagram" />
                            </a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com" target="_blank">
                                <img src="~/lib/img/fb.png" alt="facebook" />
                            </a>
                        </li>
                        <li>
                            <a href="https://www.twitter.com" target="_blank">
                                <img src="~/lib/img/link.png" alt="twitter" />
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

COMP2139_KRN_GENIUS/COMP2139_KRN_GENIUS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!-- Main Page -->
<section id="main-banner">
    <div class="main-text">
        <h1>SportsPro Technical Support</h1>
        <p>Sports management software for the sports enthusiast</p>
        <div class="main-btn">
            <a href="#admin"><span></span>Administrator</a>
            <a href="#tech"><span></span>Technician</a>
            <a href="#cont"><span></span>Contact Us</a>
        </div>
    </div>
</section>

<!-- Administtrator + Technician -->
<section id="admin">
    <div id="admin-page">
        <div class="admin-title">
            <h1>ADMINISTRATOR</h1>
            <p>A menu that allows Administrators to manage products, technicians, customers, incidents.</p>
        </div>
        <div class="admin-content">
            <div id="admin1">
                <div class="admin-img">
                    <img src="~/lib/img/admin-prod.jpg" alt="admin_products"/>
                </div>
                <div id="admin1-desc" class="admin-desc">
                    <h1>Products</h1>
                    <h6>Proin et libero sed lorem vestibulum mollis ut eget nisi. Integer erat turpis, fermentum nec molestie at.</h6>
                    <p>
                        Nullam imperdiet auctor erat, vel bibendum risus ullamcorper a. Sed sagittis at quam non feugiat. Integer vehicula diam velit, non tristique quam tristique id. Suspendisse finibus congue libero, sed faucibus ligula lacinia in. 
                    </p>
                    <div class="admin-btn">
                        <a asp-area="" asp-controller="Product" asp-action="List"><span>View Products</span></a>
                    </div>
                </div>
            </div>
            <div id="admin2">
                <div class="admin-img" id="admin2-img">
                    <img src="~/lib/img/admin-cust.jpg" alt="admin_customers" />
                </div>
                <div id="admin2-desc" class="admin-desc">
                    <h1>Customers</h1>
                    <h6>Proin et libero sed lorem vestibulum mollis ut eget nisi. Integer erat turpis, fermentum nec molestie at.</h6>
                    <p>
                        Nullam imperdiet auctor erat, vel bibendum risus ullamcorper a. Sed sagittis at quam non feugiat. Integer vehicula diam velit, non tristique quam tristique id. Suspendisse finibus congue libero, sed faucibus ligula lacinia in.
                    </p>
                    <div class="admin-btn">
                        <a asp-area="" asp-controller="Customer" asp-action="List"><span>View Customers</span></a>
                    </div>
                </div>
            </div>
            <div id="admin3">
                <div class="admin-img">
                    <img src="~/lib/img/admin-tech.jpg" alt="admin_technicians" />
                </div>
                <div id="admin3-desc" class="admin-desc">
                    <h1>Technicians</h1>
                    <h6>Proin et libero sed lorem vestibulum mollis ut eget nisi. Integer erat turpis, fermentum nec molestie at.</h6>
                    <p>
                        Nullam imperdiet auctor erat, vel bibendum risus ullamcorper a. Sed sagittis at quam non feugiat. Integer vehicula diam velit, non tristique quam tristique id. Suspendisse finibus congue libero, sed faucibus ligula lacinia in.
                    </p>
                    <div class="admin-btn">
                        <a asp-area="" asp-controller="Technician" asp-action="List"><span>View Technicians</span></a>
                    </div>
                </div>
            </div>
            <div id="admin4">
                <div class="admin-img" id="admin4-img">
                    <img src="~/lib/img/admin-incid.jpg" alt="admin_incidents" />
                </div>
                <div id="admin4-desc" class="admin-desc">
                    <h1>Incidents</h1>
                    <h6>Proin et libero sed lorem vestibulum mollis ut eget nisi. Integer erat turpis, fermentum nec molestie at.</h6>
                    <p>
                        Nullam imperdiet auctor erat, vel bibendum risus ullamcorper a. Sed sagittis at quam non feugiat. Integer vehicula diam velit, non tristique quam tristique id. Suspendisse finibus congue libero, sed faucibus ligula lacinia in.
                    </p>
                    <div class="admin-btn">
                        <a asp-area="" asp-controller="Incident" asp-action="List"><span>View Incidents</span></a>
                    </div>
                </div>
            </div>
            <div id="admin5">
                <div class="admin-img">
                    <img src="~/lib/img/admin-regis.jpg" alt="admin_registrations" />
                </div>
                <div id="admin5-desc" class="admin-desc">
                    <h1>Registrations</h1>
                    <h6>Proin et libero sed lorem vestibulum mollis ut eget nisi. Integer erat turpis, fermentum nec molestie at.</h6>
                    <p>
                        Nullam imperdiet auctor erat, vel bibendum risus ullamcorper a. Sed sagittis at quam non feugiat. Integer vehicula diam velit, non tristique quam tristique id. Suspendisse finibus congue libero, sed faucibus ligula lacinia in. 
                    </p>
                    <div class="admin-btn">
                        <a asp-area="" asp-controller="Registration" asp-action="Get"><span>View Registrations</span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="tech">
    <div id="admin-page">
        <div class="admin-title">
            <h1>TECHNICIAN</h1>
            <p>A menu that allows Technicians to update incidents.</p>
        </div>
        <div class="admin-content">
            <div id="admin6">
                <div class="admin-img" id="admin6-img">
                    <img src="~/lib/img/tech-incid-r.jpg" alt="tech_incidents" />
                </div>
                <div id="admin6-desc" class="admin-desc">
                    <h1>Incidents</h1>
                    <h6>Proin et libero sed lorem vestibulum mollis ut eget nisi. Integer erat turpis, fermentum nec molestie at.</h6>
                    <p>
                        Nullam imperdiet auctor erat, vel bibendum risus ullamcorper a. Sed sagittis at quam non feugiat. Integer vehicula diam velit, non tristique quam tristique id. Suspendisse finibus congue libero, sed faucibus ligula lacinia in. 
                    </p>
                    <div class="admin-btn">
			            <a asp-area="" asp-controller="TechIncident" asp-action="Get"><span>Update Incidents</span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>